# Generated by Django 3.0.6 on 2021-01-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='message',
        ),
    ]
